# Settings.yml
---
conf.py:
  project: Getting Started Tutorial
  copyright: 2004-2015
  version: 6.2.0
  release: 6.2.0
  intersphinx_mapping:
    t3install:
    - https://docs.typo3.org/typo3cms/InstallationGuide
    - null
    t3tsconfig:
    - https://docs.typo3.org/typo3cms/TSconfigReference
    - null
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3editors:
    - https://docs.typo3.org/typo3cms/EditorsTutorial
    - null
    t3ts45:
    - https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial
    - null
    t3templating:
    - https://docs.typo3.org/typo3cms/TemplatingTutorial/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted
    github_branch: 6.2
  latex_documents:
  - - Index
    - t3start.tex
    - Getting Started Tutorial
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
